### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by Dunnings** [pixijs/floss#29]
This project is written in typescript, yet there is no example as to how to run floss (using NPM or otherwise) with ts-node as a require as with regular mocha `mocha -r ts-node/register /path/to/code/**.*.ts`.

**Comment by bigtimebuddy** [comment]
Good suggestion, I added this wiki page. 
https://github.com/pixijs/floss/wiki/Running-TypeScript-with-Floss

**Comment by bigtimebuddy** [comment]
I'll work on adding this information to the README. That needs a dust-off anyways.
