### ISSUE TITLE
"require is not defined" in Electron >12.0.0

### ISSUE THREAD

**Issue by Vadinci** [pixijs/floss#39]
See [Electron's breaking changes list](https://www.electronjs.org/docs/breaking-changes#default-changed-contextisolation-defaults-to-true). This causes the script in index.html to break.

Simply adding `contextIsolation: false` to the options object used to create an Electron window solved the issue for me, but I haven't looked at the security implications of that.

**Comment by bigtimebuddy** [comment]
Thanks for pointing this out @Vadinci :+1:
