### ISSUE TITLE
Question: Are there examples/docs on how to test Pixi.js using floss?

### ISSUE THREAD

**Issue by mvxt** [pixijs/floss#45]
I'm pretty new to Pixi.js and was told that floss is the officially recommended way to test a Pixi.js app. Would love a couple of quick pointers/examples to get started.

**Comment by bigtimebuddy** [comment]
Nowadays, there are lots of ways to accomplish this to test in the DOM directly. I wouldn't say Floss the the preferred way, it's just what we use for our unit testing on the main repo. Floss is rather generalized solution which combines two pieces of tech: electron and mocha. 

I implemented Floss on https://github.com/pixijs/sound maybe that is a simpler example than on pixi.js to look at.

**Comment by mvxt** [comment]
Gotcha, thanks! I'll keep digging around then
