### ISSUE TITLE
Effort to port to Jest?

### ISSUE THREAD

**Issue by mimshwright** [pixijs/floss#50]
Hello, you might remember me from such issues as https://github.com/pixijs/pixijs/issues/7554

Just wanted to get a hot take about the effort it might require to port this to Jest testing / make this work to run Jest tests as well? 

Thank you!

**Comment by bigtimebuddy** [comment]
It's out of scope of this project. You may want to check out https://github.com/hustcc/jest-electron or https://github.com/facebook-atom/jest-electron-runner

**Comment by mimshwright** [comment]
Aside from some pixel values being off by one, looks like https://github.com/hustcc/jest-electron is working for me. Thank you!
