### ISSUE TITLE
What is the difference between the way FLOSS tests and using JEST alone?

### ISSUE THREAD

**Issue by 9a-aaaaaaaa** [pixijs/floss#58]
I used Jest alone to test pixi.js project and encountered various problems and reported errors. When I saw pixi.js tested by electron, I thought this way was very special, but I still didn't quite understand the test principle of FLOSS.

**Comment by 9a-aaaaaaaa** [comment]
How is it different from using Jest and Mocha alone, using Electron

**Comment by bigtimebuddy** [comment]
Floss was created when there were really no alternatives for continuous integration with a real DOM. There were ways of mocking or using a fake DOM, but not automated in-browser testing. Also, running in Electron allowed us to use webgl, critical for testing the PixiJS project.

Nowadays there are better alternatives for different testing frameworks running in CI on real browsers. Likely, we will transition to these things which have broader adoption and deprecate this home-brewed project which now seems more like tech debt.

**Comment by 9a-aaaaaaaa** [comment]
Thank you very much for your answer
